### ISSUE TITLE
"extract to function" and "extract to file" failed

### ISSUE THREAD

**Issue by kbwo** [fannheyward/coc-react-refactor#72]
related to #37 / #38 .
I'm using NeoVim v0.4.4

I'm trying to use this extension, but I keep getting same issue. 
I'm using latest version coc.nvim and coc-react-refactor.
I have tried both release branch and master branch of coc.nvim.
I also tried this configuration.
```
"coc.preferences.promptInput": false
```
but, it's still not working.
Is there any solutions?

**Comment by fannheyward** [comment]
What's the errors in `CocOpenLog`?

**Comment by kbwo** [comment]
CocOpenLog
```
2021-02-25T20:18:40.139 ERROR (pid:3162960) [extension:coc-react-refactor] - Extract JSX to function: Error: /home/kodai/src/js/booking-app/mobile/babel.config.js: Error while loading config - Cannot find module '/home/kodai/src/js/booking-app/mobile/babel.config.js'
    at webpackEmptyContext (/home/kodai/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:60138:10)
    at loadCjsDefault (/home/kodai/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:60072:42)
    at loadCjsOrMjsDefault (/home/kodai/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:60044:16)
    at loadCjsOrMjsDefault.next (<anonymous>)
    at readConfigJS (/home/kodai/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:58367:47)
    at readConfigJS.next (<anonymous>)
    at Function.<anonymous> (/home/kodai/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:58005:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/kodai/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:57850:28)
    at Function.sync (/home/kodai/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:57690:14) {
  code: 'MODULE_NOT_FOUND'
}
```

babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: 'react-native-dotenv',
      },
    ],
  ],
};

```
I noticed if babel.config.js removed, this extension works.

If this babel.config.js is like this, also keep getting same issue.

```
module.exports = {};
```

**Comment by kbwo** [comment]
I noticed this issue is same as #15
I'm sorry.
